workspace = { members = ["readonly-dummy-server"] }
[package]
name = "riel"
version = "0.0.3"
edition = "2021"

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

[profile.release]
opt-level = "z"
lto = true
